### ISSUE TITLE
Inkscape 1.0 Issues

### ISSUE THREAD

**Issue by dapperfu** [jed-frey/InkscapeLaserGCode#1]
```
laser2.py:116: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "main curve": simplestyle.formatStyle(
laser2.py:126: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:134: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:142: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:150: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:160: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:168: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:176: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:184: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:194: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:202: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:210: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:218: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:228: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:236: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:244: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:252: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:262: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:270: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:278: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:286: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:296: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:304: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:312: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:320: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:330: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:338: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:346: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:354: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:364: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc0": simplestyle.formatStyle(
laser2.py:372: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "biarc1": simplestyle.formatStyle(
laser2.py:380: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "line": simplestyle.formatStyle(
laser2.py:388: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area": simplestyle.formatStyle(
laser2.py:397: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area artefact": simplestyle.formatStyle(
laser2.py:400: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "area artefact arrow": simplestyle.formatStyle(
laser2.py:403: DeprecationWarning: simplestyle.formatStyle -> str(inkex.Style(a))
  "dxf_points": simplestyle.formatStyle({"stroke": "#ff0000", "fill": "#ff0000"}),
laser2.py:3324: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3332: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3340: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3348: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3357: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3366: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3375: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3383: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3391: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3400: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3409: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3418: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3427: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3436: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3445: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3453: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3462: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3471: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3479: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:3488: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
laser2.py:4601: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  e.affect()
laser2.py:4129: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  elif i.get("id") in self.selected:
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "laser2.py", line 4601, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "laser2.py", line 4495, in effect
    self.get_info()
  File "laser2.py", line 4137, in get_info
    recursive_search(self.document.getroot(), self.document.getroot())
  File "laser2.py", line 4094, in recursive_search
    recursive_search(i, i)
  File "laser2.py", line 4130, in recursive_search
    self.error(
  File "laser2.py", line 4042, in error
    print_(s)
  File "laser2.py", line 1927, in print_
    s = str(unicode(s).encode("unicode_escape")) + " "
NameError: name 'unicode' is not defined
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='laser2.log' mode='a' encoding='UTF-8'>
```

**Comment by dapperfu** [comment]
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0
